#!/bin/bash

###########################################################################################################
# CHAPTER 11: 
# Basic Script Building
#
#
###################################### bc basics
#
# to use bc in sh scripts,
# more practical with inline input redirection:
#
#

var1=10.9
var2=3.2

ans=$(bc << EOF
scale=4
exp1=($var1 * $var2)
exp2=($var1 + $var2)
exp1 + exp2
EOF
)

echo "the answer is $ans"
