#!/bin/bash
###########################################################################################################
# CHAPTER 13: 
# More Structured Commands
#
#
######################################## looping: practical example: executable files in $PATH folders
#
#

IFSX=$IFS
IFS=:

for folder in $PATH
do
	echo "for-loop in $PATH: $folder"
	for file in $folder/*
	do
		if [ -x "$file" ]
		then
			echo "-x file in $folder: $file"
		fi
	done
done > Chap13PATHsearchoutput.txt

IFS=$IFSX
