#!/bin/bash

###########################################################################################################
# CHAPTER 10: 
# Working with Editors
#
#
# INDEX:
# vim
# vim basics
# nano (more simple than vim)
#
#
###################################### vim
#
#	currently, only the tiny ver of vim is installed, as checked by:
#	readlink -f /usr/bin/vi
#
#
###################################### vim basics
#
#	vi filename opens filename in normal mode for editing of file;
#	type :i for input mode
#
#	(c.f. help)
#
#
###################################### nano (more simple than vim)
#
#	start:
#	nano filename
#
#	
#
#	...
#
#
#
#
#
###########################################################################################################
